# Artificial Neural Network

### Importing the libraries

In [ ]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [ ]:
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [ ]:
dataset = pd.read_excel("Folds5x2_pp.xlsx")
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(X)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


### Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

## Part 2 - Building the ANN

### Initializing the ANN

In [ ]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [ ]:
ann.add(tf.keras.layers.Dense(units=1))

## Part 3 - Training the ANN

### Compiling the ANN

In [ ]:
ann.compile(optimizer='Adam', loss='mean_squared_error')

### Training the ANN model on the Training set

In [ ]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 6481.5171
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 136.4808
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 127.5895
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 118.2579
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 108.5053
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 98.8235
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 89.6451
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 80.9971
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 72.9189
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 66.1308
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 60.0506
Epoch 12/100
240/240 [==============================] - 0s 1ms/step - loss: 55.

### Predicting the results of the Test set

In [ ]:
y_pred = ann.predict(X_test)
np.set_printoptions(precision=2)
np.concatenate(y_pred.reshape(len(y_pred), 1), X_test.reshape(len(X_test), 1))